### ISSUE TITLE
UI White-out bug

### ISSUE THREAD

**Issue by Zebouski** [Warlockbugs/impulse-booster#7]
Impulse booster seems to be the culprit causing some bits and pieces of the UI to white out.
![image](https://cdn.discordapp.com/attachments/466627627554439178/1107099981749420122/image.png)
![image](https://cdn.discordapp.com/attachments/466627627554439178/1107105665966674042/image.png)
I and others have experienced this and disabling impulse booster fixes this

**Comment by Warlockbugs** [comment]
Never encountered such an issue, no matter windows or wine. Which client version is used? Any other specific addons installed?

**Comment by Zebouski** [comment]
This was replicated by me and a bunch of other turtle wow players, some of us with many addons, and i've replicated it with just IB. 

![image](https://github.com/Warlockbugs/impulse-booster/assets/11151284/51687d7b-570b-4903-b958-eed69a05cb2c)

But, Turtle wow is modded 1.12 and it does ship its own UI modifications inside the custom .mpq files, so maybe some lua within there is the culprit. And yeah if you've never ever seen this bug on normal 1.12, then yeah I could take this to the turtle wow bug tracker instead.

**Comment by Warlockbugs** [comment]
It is possible that some modified UI elements are not behaving properly when graphics engine is forcefully restarted before UI is finalized. I would check if it happens with opengl renderer to rule out possible dxvk interference. I had this addon virtually unchanged in the way it interacts with the client for many years and different os and hardware and this is the first time i am seeing anything like this.
There is logic built in to calculate when number of installed addons is high enough to even warrant a graphics restart to speed UI loading up, otherwise you waste more time restarting the renderer when all you have is just a couple addons enabled. That may appear as intermittent issue, but what that really means is that IB is active and game is being redrawn during UI loading when this happens.
A possible workaround is doing a UI reload once again by hand. But that just means that something is not being loaded properly.

**Comment by Warlockbugs** [comment]
Reported to be caused by third party graphics API translation layer (DXVK) with no relation to the addon itself, apart from graphics redraw being a possible trigger for the bug.
